apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  namespace: teja-ns
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: VAR1
          valueFrom:
            configMapKeyRef:
              name: nginx-configmap
              key: env

