apiVersion: v1
kind: Service
metadata:
  namespace: teja-ns
  name: nginx-service
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
  selector:
      app: nginx


