apiVersion: v1
kind: Pod
metadata:
  name: pod-init-container
  namespace: teja-ns
spec:
  initContainers:
    - name: sleepy
      image: alpine
      command: ['sleep', '60']
  containers:
    - name: web
      image: nginx


