apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: my-azurefile-pvc 
  namespace: teja-ns 
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 10Gi 
  storageClassName: my-azurefile
