apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: teja-ns
  name: rs
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
  template:
    metadata:
      name: nginx-rs
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
