apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  namespace: teja-ns
spec:
  replicas: 1
  serviceName: "mongo"
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin" 
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          volumeMounts:
            - name: data
              mountPath: /data/db
            - name: logs
              mountPath: /var/log/mongodb

        - name: log-collector
          image: alpine:latest
          command: ["sh", "-c", "while true; do tail -f /var/log/mongodb/mongodb.log; sleep 1; done"]
          volumeMounts:
            - name: logs
              mountPath: /var/log/mongodb

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: my-azurefile-pvc

        - name: logs
          persistentVolumeClaim:
            claimName: my-azurefile-pvc-log

