apiVersion: v1
kind: Pod
metadata:
  name: nginx-toleration-pod
  namespace: teja-ns
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "200m"
          memory: "200Mi"
  tolerations:
    - key: "nginx-enabled"
      operator: "Equal"
      value: "false"
      effect: "NoSchedule"
  #IT WENT NODE 2 instead of node 1.. to strictly place it use node affinity
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "tier"
                operator: "In"
                values:
                  - "dev"

